const singleData = [
  {item:"艾利達莊園",country:"巴拿馬",process:"厭氧緩慢日曬",roast:"淺焙",taste:"果香微酸",flavor:"楊桃、紅酒、洋甘菊",priceQuarter:"$500 (100g)",priceHalf:"",drip:""},
  {item:"果漾藍莓",country:"哥倫比亞",process:"藍莓水洗",roast:"淺焙",taste:"果香微酸",flavor:"藍莓、水果軟糖、紅烏龍",priceQuarter:"$370 (100g)",priceHalf:"",drip:"$35"},
  {item:"初見玫瑰",country:"哥倫比亞",process:"玫瑰水洗",roast:"淺焙",taste:"果香微酸",flavor:"開心果、奶酒、偉特糖",priceQuarter:"$370 (100g)",priceHalf:"",drip:"$35"},
  {item:"哈特曼莊園",country:"巴拿馬",process:"日曬",roast:"淺焙",taste:"果香微酸",flavor:"雞蛋花、小紅莓、奶油",priceQuarter:"$370 (100g)",priceHalf:"",drip:"$35"},
  {item:"長老的最愛",country:"哥倫比亞",process:"小米酒槽特殊水洗",roast:"淺焙",taste:"果香微酸",flavor:"熱紅酒、葡萄柚、小紅莓",priceQuarter:"$370 (100g)",priceHalf:"",drip:"$35"},
  {item:"青蘋果",country:"哥倫比亞",process:"水洗",roast:"淺焙",taste:"果香微酸",flavor:"檸檬磅蛋糕、桂花、芒果",priceQuarter:"$370 (100g)",priceHalf:"",drip:"$35"},
  {item:"哈蜜瓜挫挫",country:"哥倫比亞",process:"特殊水洗",roast:"淺焙",taste:"果香微酸",flavor:"哈蜜瓜、楓糖、香瓜",priceQuarter:"$370 (100g)",priceHalf:"",drip:"$35"},
  {item:"紅衫處理廠",country:"哥倫比亞",process:"厭氧日曬",roast:"淺焙",taste:"果香微酸",flavor:"玫瑰紅茶、葡萄軟糖、橙皮",priceQuarter:"$370 (100g)",priceHalf:"",drip:"$35"},
  {item:"草莓樂園",country:"哥倫比亞",process:"酵母水洗",roast:"淺焙",taste:"果香微酸",flavor:"櫻桃、草莓乾、奶油酥餅",priceQuarter:"$370 (100g)",priceHalf:"",drip:"$35"},
  {item:"花境藝妓",country:"哥倫比亞",process:"水洗",roast:"淺焙",taste:"果香微酸",flavor:"百里香、葡萄柚、梅子綠茶",priceQuarter:"$370 (100g)",priceHalf:"",drip:"$35"},
  {item:"西施-西達摩",country:"衣索比亞",process:"日曬",roast:"淺焙",taste:"微酸核果",flavor:"茉莉花、小麥、蘋果",priceQuarter:"$205",priceHalf:"$370",drip:"$26"},
  {item:"瓦米娜",country:"衣索比亞",process:"厭氧日曬",roast:"淺焙",taste:"果香微酸",flavor:"草莓餅乾、白桃、玫瑰花",priceQuarter:"$205",priceHalf:"$370",drip:"$26"},
  {item:"夏茉卡",country:"衣索比亞 耶加",process:"水洗",roast:"淺焙",taste:"果香微酸",flavor:"蜜蘋果、青茶、蔗糖",priceQuarter:"$205",priceHalf:"$370",drip:"$26"},
  {item:"艾迪朵",country:"衣索比亞 耶加",process:"日曬",roast:"淺焙",taste:"果香微酸",flavor:"野薑花、乾梅、玄米茶",priceQuarter:"$205",priceHalf:"$370",drip:"$26"},
  {item:"金礦山",country:"衣索比亞 古吉",process:"日曬",roast:"淺焙",taste:"果香微酸",flavor:"黑蜜李、麝香葡萄、蓮霧",priceQuarter:"$205",priceHalf:"$370",drip:"$26"},
  {item:"水風鈴",country:"衣索比亞 古吉",process:"紅蜜",roast:"淺焙",taste:"果香微酸",flavor:"檸檬塔、荔枝蜜、甜柿",priceQuarter:"$205",priceHalf:"$370",drip:"$26"},
  {item:"切切蕾",country:"衣索比亞",process:"水洗",roast:"淺焙",taste:"果香微酸",flavor:"金桔、百合花、紅烏龍",priceQuarter:"$205",priceHalf:"$370",drip:"$26"},
  {item:"沃卡村",country:"衣索比亞",process:"日曬",roast:"淺焙",taste:"果香微酸",flavor:"香草、卡士達、青森蘋果",priceQuarter:"$205",priceHalf:"$370",drip:"$26"},
  {item:"沃卡村",country:"衣索比亞",process:"黃蜜",roast:"淺焙",taste:"果香微酸",flavor:"覆盆子、麥芽糖、葡萄軟糖",priceQuarter:"$205",priceHalf:"$370",drip:"$26"},
  {item:"邦貝",country:"衣索比亞",process:"日曬",roast:"淺焙",taste:"果香微酸",flavor:"柑橘、鳳梨、龍眼蜜",priceQuarter:"$205",priceHalf:"$370",drip:"$26"},
  {item:"綠翡翠",country:"哥倫比亞",process:"水洗",roast:"中焙",taste:"不酸堅果",flavor:"可可、鐵觀音、堅果奶",priceQuarter:"$205",priceHalf:"$370",drip:"$26"},
  {item:"希望莊園",country:"瓜地馬拉",process:"水洗",roast:"中焙",taste:"不酸核果",flavor:"焦糖、杏仁、榛果",priceQuarter:"$205",priceHalf:"$370",drip:"$26"},
  {item:"美蘇",country:"泰國",process:"水洗",roast:"中焙",taste:"不酸堅果",flavor:"榛果、巧克力、奶油",priceQuarter:"$205",priceHalf:"$370",drip:"$26"},
  {item:"喜拉朵",country:"巴西",process:"半水洗",roast:"中焙",taste:"不酸核果",flavor:"麥芽、堅果、奶油",priceQuarter:"$205",priceHalf:"$370",drip:"$26"},
  {item:"守望者",country:"尼加拉瓜",process:"水洗",roast:"中焙",taste:"微酸核果",flavor:"杏仁果、紅糖、羅望子",priceQuarter:"$205",priceHalf:"$370",drip:"$26"},
  {item:"巧克力情人",country:"薩爾瓦多",process:"水洗",roast:"中焙",taste:"微酸核果",flavor:"青蘋果、蕎麥、榛果",priceQuarter:"$205",priceHalf:"$370",drip:"$26"},
  {item:"呼麻",country:"哥倫比亞",process:"水洗",roast:"中深焙",taste:"不酸",flavor:"熱帶水果、黑巧克力、杏仁",priceQuarter:"$205",priceHalf:"$370",drip:"$26"},
  {item:"喜拉朵",country:"巴西",process:"半水洗",roast:"中深焙",taste:"不酸",flavor:"可可、黑糖、奶油",priceQuarter:"$205",priceHalf:"$370",drip:"$26"},
  {item:"檸檬樹莊園",country:"尼加拉瓜",process:"水洗",roast:"中深焙",taste:"不酸",flavor:"黑巧克力、蔗糖、烏梅",priceQuarter:"$205",priceHalf:"$370",drip:"$26"},
  {item:"美蘇",country:"泰國",process:"水洗",roast:"中深焙",taste:"不酸",flavor:"堅果、黑巧克力、蔗糖",priceQuarter:"$205",priceHalf:"$370",drip:"$26"}
];